name: Test

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        racket-variant: ['CS', 'BC']
        racket-version: ['8.0', '8.1', 'current']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: Install dependencies on Linux
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ python cmake         
    - name: Install dependencies on Macos
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install python cmake ninja
    - name: Compile binaryen
      run: |
        git clone --depth 1 https://github.com/WebAssembly/binaryen.git binaryen-src
        cd binaryen-src
        cmake .
        make -j2
        sudo make install
    - name: Install pkg
      run: raco pkg install -D --auto $PWD
    - name: Run unit tests
      run: raco test .
    - name: Run wingo_fact.scm with wingo-raw
      run: racket tests/wingo-raw.rkt tests/wingo-input/wingo_fact.scm
    - name: Run wingo_zero.scm with wingo-raw
      run: racket tests/wingo-raw.rkt tests/wingo-input/wingo_zero.scm
    - name: Run wingo_const.scm with wingo-raw
      run: racket tests/wingo-raw.rkt tests/wingo-input/wingo_const.scm
    - name: Run wingo_fact.scm with wingo
      run: racket tests/wingo.rkt tests/wingo-input/wingo_fact.scm
    - name: Run wingo_zero.scm with wingo
      run: racket tests/wingo.rkt tests/wingo-input/wingo_zero.scm
    - name: Run wingo_const.scm with wingo
      run: racket tests/wingo.rkt tests/wingo-input/wingo_const.scm
